'use strict';

module.exports = [
	{ name: 'Austria' },
	{ name: 'Belgium' },
	{ name: 'Bulgaria' },
	{ name: 'Croatia' },
	{ name: 'Cyprus' },
	{ name: 'Czech Republic' },
	{ name: 'Denmark' },
	{ name: 'Estonia' },
	{ name: 'Finland' },
	{ name: 'France' },
	{ name: 'Germany' },
	{ name: 'Greece' },
	{ name: 'Hungary' },
	{ name: 'Iceland' },
	{ name: 'Ireland' },
	{ name: 'Italy' },
	{ name: 'Latvia' },
	{ name: 'Liechtenstein' },
	{ name: 'Lithuania' },
	{ name: 'Luxembourg' },
	{ name: 'Malta' },
	{ name: 'Netherlands' },
	{ name: 'Norway' },
	{ name: 'Poland' },
	{ name: 'Portugal' },
	{ name: 'Romania' },
	{ name: 'Slovakia' },
	{ name: 'Slovenia' },
	{ name: 'Spain' },
	{ name: 'Sweden' },
	{ name: 'United Kingdom' },
];
