'use strict';

var countries = [
	{ code: 'AT', currency: 'EUR', name: 'Austria' },
	{ code: 'BE', currency: 'EUR', name: 'Belgium' },
	{ code: 'BG', currency: 'BGN', name: 'Bulgaria' },
	{ code: 'HR', currency: 'HRK', name: 'Croatia' },
	{ code: 'CY', currency: 'EUR', name: 'Cyprus' },
	{ code: 'CZ', currency: 'CZK', name: 'Czech Republic' },
	{ code: 'DK', currency: 'DKK', name: 'Denmark' },
	{ code: 'EE', currency: 'EUR', name: 'Estonia' },
	{ code: 'FI', currency: 'EUR', name: 'Finland' },
	{ code: 'FR', currency: 'EUR', name: 'France' },
	{ code: 'DE', currency: 'EUR', name: 'Germany' },
	{ code: 'GR', currency: 'EUR', name: 'Greece' },
	{ code: 'HU', currency: 'HUF', name: 'Hungary' },
	{ code: 'IS', currency: 'ISK', name: 'Iceland' },
	{ code: 'IE', currency: 'EUR', name: 'Ireland' },
	{ code: 'IT', currency: 'EUR', name: 'Italy' },
	{ code: 'LV', currency: 'EUR', name: 'Latvia' },
	{ code: 'LI', currency: 'CHF', name: 'Liechtenstein' },
	{ code: 'LT', currency: 'EUR', name: 'Lithuania' },
	{ code: 'LU', currency: 'EUR', name: 'Luxembourg' },
	{ code: 'MT', currency: 'EUR', name: 'Malta' },
	{ code: 'NL', currency: 'EUR', name: 'Netherlands' },
	{ code: 'NO', currency: 'NOK', name: 'Norway' },
	{ code: 'PL', currency: 'PLN', name: 'Poland' },
	{ code: 'PT', currency: 'EUR', name: 'Portugal' },
	{ code: 'RO', currency: 'RON', name: 'Romania' },
	{ code: 'SK', currency: 'EUR', name: 'Slovakia' },
	{ code: 'SI', currency: 'EUR', name: 'Slovenia' },
	{ code: 'ES', currency: 'EUR', name: 'Spain' },
	{ code: 'SE', currency: 'SEK', name: 'Sweden' },
	{ code: 'GB', currency: 'GPB', name: 'United Kingdom' },
	{ code: 'CH', currency: 'CHF', name: 'Switzerland' },
	{ code: 'SM', currency: 'EUR', name: 'San Marino' },
	{ code: 'MC', currency: 'EUR', name: 'Monaco' },
	{ code: 'GL', currency: 'DKK', name: 'Greenland' },
	{ code: 'GI', currency: 'GIP', name: 'Gibraltar' },
	{ code: 'FO', currency: 'DKK', name: 'Faroe Islands' },
];

module.exports = countries;
